# file: base_ubuntu/tasks/common.yml

---
- name: base_ubuntu | common | aptitude upgrade
  apt: update_cache=yes upgrade=yes

- name: base_ubuntu | common | apt_get install python_software_properties
  apt: name=python-software-properties state=present

- name: base_ubuntu | common | add-apt-repository apt_repositories
  apt_repository: repo={{ item }}
  with_items: base_ubuntu.common.apt_repositories

- name: base_ubuntu | common | aptitude update
  apt: update_cache=yes

- name: base_ubuntu | common | aptitude purge absent_packages
  apt: name={{ item }} state=absent
  with_items: base_ubuntu.common.absent_packages

- name: base_ubuntu | common | aptitude install curl
  apt: name=curl state=present

- name: base_ubuntu | common | apt_get purge absent_packages
  apt: name={{ item }} state=absent
  with_items: base_ubuntu.common.absent_packages

# source packages --------------------------------------------------------- {{{
- name: base_ubuntu | common | curl source_packages.tar
  shell: "curl {{ item.src }} | tar xz chdir=/tmp creates={{ item.directory }}"
  with_items: base_ubuntu.common.source_packages.tar

- name: base_ubuntu | common | git clone source_packages.git
  git: repo={{ item.src }} dest={{ item.directory }}
  with_items: base_ubuntu.common.source_packages.git

- name: base_ubuntu | common | ./configure source_packages.tar
  command: "{{ item.configure_command }} chdir={{ item.directory }} creates={{ item.configure_creates }}"
  with_items: base_ubuntu.common.source_packages.tar

- name: base_ubuntu | common | ./configure source_packages.git
  command: "{{ item.configure_command }} chdir={{ item.directory }} creates={{ item.configure_creates }}"
  with_items: base_ubuntu.common.source_packages.git

- name: base_ubuntu | common | make source_packages.tar
  command: "{{ item.make_command }} chdir={{ item.directory }} creates={{ item.make_creates }}"
  with_items: base_ubuntu.common.source_packages.tar

- name: base_ubuntu | common | make source_packages.git
  command: "{{ item.make_command }} chdir={{ item.directory }} creates={{ item.make_creates }}"
  with_items: base_ubuntu.common.source_packages.git

- name: base_ubuntu | common | make install source_packages.tar
  command: "{{ item.make_install_command }} chdir={{ item.directory }} creates={{ item.make_install_creates }}"
  with_items: base_ubuntu.common.source_packages.tar

- name: base_ubuntu | common | make install source_packages.git
  command: "{{ item.make_install_command }} chdir={{ item.directory }} creates={{ item.make_install_creates }}"
  with_items: base_ubuntu.common.source_packages.git
# /source packages -------------------------------------------------------- }}}

- name: base_ubuntu | common | apt_get install apt_packages
  apt: pkg={{ item }} state=present
  with_items: base_ubuntu.common.apt_packages

# python packages --------------------------------------------------------- {{{
- name: base_ubuntu | common | easy_install pip
  easy_install: name=pip

- name: base_ubuntu | common | pip install python_packages.requirements
  pip: name={{ item }} state=present
  with_items: base_ubuntu.python_packages.requirements
# /python packages -------------------------------------------------------- }}}
