# file: base_ubuntu/tasks/common.yml

---
- name: common | aptitude upgrade
  apt: update_cache=yes upgrade=yes

- name: common | apt_get install python_software_properties
  apt: name=python-software-properties state=present

- name: common | add-apt-repository apt_repositories
  apt_repository: "repo='{{ item }}' state=present"
  with_items: base_ubuntu.common.apt_repositories

- name: common | add-apt-key apt_keys
  apt_key: "url='{{ item }}' state=present"
  with_items: base_ubuntu.common.apt_keys

- name: common | aptitude update
  apt: update_cache=yes

- name: common | aptitude purge absent_packages
  apt: name={{ item }} state=absent
  with_items: base_ubuntu.common.absent_packages

- name: common | aptitude install curl
  apt: name=curl state=present

- name: common | apt-get purge absent_packages
  apt: name={{ item }} state=absent
  with_items: base_ubuntu.common.absent_packages

- name: common | apt-get install git
  apt: name=git state=present

- name: common | apt_get install apt_packages
  apt: pkg={{ item }} state=present
  with_items: base_ubuntu.common.apt_packages

# python packages --------------------------------------------------------- {{{
- name: common | easy_install pip
  easy_install: name=pip

- name: common | pip install python_packages.requirements
  pip: name={{ item }} state=present
  with_items: base_ubuntu.python_packages.requirements
# /python packages -------------------------------------------------------- }}}

# source packages --------------------------------------------------------- {{{
- name: common | curl source_packages.tar
  shell: "curl {{ item.src }} | tar xz chdir=/tmp creates={{ item.directory }}"
  with_items: base_ubuntu.common.source_packages.tar

- name: common | git clone source_packages.git
  git: repo={{ item.src }} dest={{ item.directory }}
  with_items: base_ubuntu.common.source_packages.git

- name: common | ./configure source_packages.tar
  command: "{{ item.configure_command }} chdir={{ item.directory }} creates={{ item.configure_creates }}"
  with_items: base_ubuntu.common.source_packages.tar

- name: common | ./configure source_packages.git
  command: "{{ item.configure_command }} chdir={{ item.directory }} creates={{ item.configure_creates }}"
  with_items: base_ubuntu.common.source_packages.git

- name: common | make source_packages.tar
  command: "{{ item.make_command }} chdir={{ item.directory }} creates={{ item.make_creates }}"
  with_items: base_ubuntu.common.source_packages.tar

- name: common | make source_packages.git
  command: "{{ item.make_command }} chdir={{ item.directory }} creates={{ item.make_creates }}"
  with_items: base_ubuntu.common.source_packages.git

- name: common | make install source_packages.tar
  command: "{{ item.make_install_command }} chdir={{ item.directory }} creates={{ item.make_install_creates }}"
  with_items: base_ubuntu.common.source_packages.tar

- name: common | make install source_packages.git
  command: "{{ item.make_install_command }} chdir={{ item.directory }} creates={{ item.make_install_creates }}"
  with_items: base_ubuntu.common.source_packages.git
# /source packages -------------------------------------------------------- }}}

# ruby gems --------------------------------------------------------------- {{{
- name: common | gem install bundler
  command: /usr/local/bin/gem install bundler creates=/usr/local/bin/bundle
# /ruby gems -------------------------------------------------------------- }}}
