# file: ansible/roles/base_ubuntu/tasks/vim.yml

---
- name: base_ubuntu | vim | hg clone vim
  hg: repo=${base_ubuntu.vim.repo} dest=${base_ubuntu.vim.dest}

- name: base_ubuntu | vim | configure vim
  shell: ./configure --with-features=huge --enable-rubyinterp --enable-pythoninterp --with-python-config-dir=/usr/lib/python2.7-config --enable-perlinterp --enable-cscope --prefix=${base_ubuntu.vim.prefix} chdir=${base_ubuntu.vim.dest} creates=${base_ubuntu.vim.dest}/src/auto/config.mk

- name: base_ubuntu | vim | make vim
  shell: make VIMRUNTIMEDIR=${base_ubuntu.vim.runtimedir} chdir=${base_ubuntu.vim.dest} creates=${base_ubuntu.vim.runtimedir}

- name: base_ubuntu | vim | make install vim
  sudo: yes
  shell: make install chdir=${base_ubuntu.vim.dest} creates=${base_ubuntu.vim.executable}
